name: getx_clean_arch
description: "A CLI tool for scaffolding and managing Flutter projects with GetX and Clean Architecture."
version: 0.0.5
repository: https://github.com/your_username/getx_clean_arch
issue_tracker: https://github.com/your_username/getx_clean_arch/issues
topics:
  - cli
  - flutter
  - getx
  - clean-architecture
  - generator

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  args: ^2.4.2
  mason_logger: ^0.2.10
  path: ^1.9.0
  recase: ^4.1.0
  dart_style: ^2.3.2
  dcli: ^4.0.1
  get: ^4.7.3
  yaml: ^3.1.3

executables:
  getxcli:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
